### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by alexsenatore** [e0ipso/plugnplay#59]
I tried to run the installation of ContentaJS, which depends on plugnplay@3.5.0 on Windows.
During "npm install" execution I'm getting the following error.

> Try 'rm --help' for more information.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plugnplay@3.5.0 build: `rm -fr lib; flow-remove-types --all src/ --out-dir lib/ && copy ./src/**/plugnplay.yml lib && flow-copy-source src lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the plugnplay@3.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<----removed------>\Roaming\npm-cache\_logs\2019-02-05T13_33_45_149Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plugnplay@3.5.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the plugnplay@3.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<----removed------>\AppData\Roaming\npm-cache\_logs\2019-02-05T13_33_55_995Z-debug.log

Looks like that `plugnplay` is not using the `rimraf` module but  the UNIX `rm` command also on Windows.

**Comment by mcmonkeys1** [comment]
this same error has returned in 2021:
`> npm  install plugnplay
npm WARN deprecated require-subvert@0.1.0: no longer maintained
npm ERR! code 1
npm ERR! path C:\Users\ros\Desktop\ARMM1\test-nodejs-harness\node_modules\plugnplay
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build
npm ERR! > plugnplay@3.13.0 build
npm ERR! > rimraf lib && flow-remove-types --all src/ --out-dir lib/ && copy ./src/**/plugnplay.yml lib && flow-copy-source src lib
npm ERR!
npm ERR! The syntax of the command is incorrect.
npm ERR! src\PluginLoaderBase.js
npm ERR!  ↳ lib\PluginLoaderBase.js
npm ERR! src\PluginLoaderFactory.js
npm ERR!  ↳ lib\PluginLoaderFactory.js
npm ERR! src\PluginManager.js
npm ERR!  ↳ lib\PluginManager.js
npm ERR! src\PluginTypeLoaderBase.js
npm ERR!  ↳ lib\PluginTypeLoaderBase.js

npm ERR! A complete log of this run can be found in:
...`
