### ISSUE TITLE
License Issues

### ISSUE THREAD

**Issue by DawnImpulse** [e0ipso/plugnplay#78]
Hey, so I want to use this package in my much broader platform which I will be releasing under ISC license. Now since this package is under GPL, that's an issue for me. Is there some way we can work it out?

**Comment by e0ipso** [comment]
According to the Free Software Foundation, the ISC license is compatible with GPL. See https://www.gnu.org/licenses/license-list.html#ISC

In any case, I am curious to know what you will be building :-)

**Comment by DawnImpulse** [comment]
Oh cool. And it is actually going to be an authentication solution. So I hope that you don't have any issues regarding my product release under ISC license while using this library ?

**Comment by DawnImpulse** [comment]
Hey @e0ipso, you cool with using this library in my open-source product under the ISC license?

**Comment by e0ipso** [comment]
@DawnImpulse I give you written consent for your project (but not for derivatives of it), as long as the final client (or any of the intermediary contractors) are involved in military operations or weapons manufacture or dealing.

Is that good for your use case?

**Comment by DawnImpulse** [comment]
My platform is going to be an open platform providing authentication solution simply :) Something like Auth0 / Ory / Apereo CAS etc. Would that be cool?

**Comment by e0ipso** [comment]
That will be :cool:. Consider written consent granted.

**Comment by e0ipso** [comment]
Fixed a very meaningful typo in https://github.com/e0ipso/plugnplay/issues/78#issuecomment-726145512.
