### ISSUE TITLE
Instance dependencies

### ISSUE THREAD

**Issue by Revadike** [e0ipso/plugnplay#85]
I'd like Plugin2 to use an instance of Plugin1. It cannot function or be instantiated without Plugin1. How does one do this?

**Comment by e0ipso** [comment]
Maybe this example is helpful: https://github.com/js-widgets/js-widgets/blob/master/packages/js-widgets-ingestion-gh-releases/src/plugnplay.yml

**Comment by Revadike** [comment]
Not helpful. What if Plugin3 needs the same instance of Plugin1, as Plugin2 needs?
